import type { BuiltinRecipe } from './recipe.types';

export const BUILTIN_RECIPES: BuiltinRecipe[] = [
  {
    id: 'tree.select.reload',
    label: 'Tree.select -> reload',
    trigger: 'Tree 节点选中',
    action: '刷新目标列表并重置分页',
    targetHint: 'table/list',
    promptText: 'Tree.select -> reload(target, { resetPage: true })',
    checklistText: '实现树选中后刷新目标列表并回到第 1 页。',
  },
  {
    id: 'master.rowClick.detail',
    label: 'Master.rowClick -> load detail',
    trigger: '主表行点击',
    action: '加载明细区域数据',
    targetHint: 'detail/form/card',
    promptText: 'Master.rowClick -> loadDetail(target)',
    checklistText: '实现主从联动：点击主表行后加载明细。',
  },
  {
    id: 'search.submit.reload',
    label: 'Search.submit -> reload & reset',
    trigger: '搜索提交',
    action: '刷新数据并重置分页',
    targetHint: 'table/list',
    promptText: 'Search.submit -> reload(target, { resetPage: true })',
    checklistText: '实现搜索提交后刷新数据并重置分页。',
  },
  {
    id: 'dialog.submit.refresh',
    label: 'Dialog.submit -> close & refresh',
    trigger: '弹窗提交成功',
    action: '关闭弹窗并刷新父列表',
    targetHint: 'dialog + table',
    promptText: 'Dialog.submit.success -> close(dialog) & reload(table)',
    checklistText: '实现弹窗提交成功后自动关闭并刷新列表。',
  },
  {
    id: 'tabs.change.lazyload',
    label: 'Tabs.change -> lazy load',
    trigger: 'Tab 切换',
    action: '首次进入时加载数据',
    targetHint: 'tab content',
    promptText: 'Tabs.change -> lazyLoad(tabContent)',
    checklistText: '实现 Tab 首次激活时加载，重复切换不重复请求。',
  },
  {
    id: 'row.action.drawer',
    label: 'Row.action -> open drawer',
    trigger: '行操作按钮点击',
    action: '打开抽屉并带入行数据',
    targetHint: 'drawer',
    promptText: 'Row.action -> open(drawer, rowData)',
    checklistText: '实现行操作打开抽屉并回填行上下文。',
  },
  {
    id: 'row.action.dialog',
    label: 'Row.action -> open dialog',
    trigger: '行操作按钮点击',
    action: '打开弹窗并带入行数据',
    targetHint: 'dialog',
    promptText: 'Row.action -> open(dialog, rowData)',
    checklistText: '实现行操作打开弹窗并回填行上下文。',
  },
  {
    id: 'form.reset.clear',
    label: 'Form.reset -> clear target',
    trigger: '表单重置',
    action: '清空目标筛选状态',
    targetHint: 'table/list',
    promptText: 'Form.reset -> clearFilters(target)',
    checklistText: '实现表单重置后清空目标筛选参数。',
  },
  {
    id: 'batch.select.export',
    label: 'Batch.select -> export',
    trigger: '批量勾选后导出',
    action: '导出勾选数据',
    targetHint: 'table',
    promptText: 'Batch.select -> export(selectedRows)',
    checklistText: '实现批量勾选导出能力。',
  },
  {
    id: 'custom.manual',
    label: 'Custom',
    trigger: '自定义触发',
    action: '按描述执行',
    targetHint: 'custom',
    promptText: 'Custom recipe (see leaf description)',
    checklistText: '按页面描述补齐自定义联动。',
  },
];

export function getRecipeById(id: string): BuiltinRecipe | undefined {
  return BUILTIN_RECIPES.find(item => item.id === id);
}
